version: '3.8'

services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
  database:
    image: library/mongo:4.0.4
    container_name: gitit-container-db
    hostname: mongodb
    volumes:
      - ./.docker/mongodb/mongod.conf:etc/mongod.conf
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    command: ["-f", "/etc/mongod.conf.orig"]
