version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./api:/api
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - database
    command: yarn start
  database:
    image: library/mongo:4.0.4
    container_name: gitit-container-db
    hostname: mongo
    restart: always
    volumes:
      #      - ./.docker/mongodb/mongod.conf.orig:/etc/mongod.conf.orig
      #      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./.scripts/init-mongo.sh:/docker-entrypoint-initdb.d/
      - ./.docker/mongodb/db/:/data/db/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    command: ["-f", "/etc/mongod.conf.orig"]
